name: Validate GitHub Actions Workflow

on:
  push:
    paths:
      - '.github/workflows/ci-cd.yml'

jobs:
  validate:
    name: Validate Workflow
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Basic YAML syntax check
      run: |
        if grep -q "^[[:space:]]*[^[:space:]#]" .github/workflows/ci-cd.yml; then
          echo "Basic syntax check passed"
        else
          echo "File appears to be empty or contains only comments"
          exit 1
        fi
        
    - name: Install actionlint
      run: |
        bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        
    - name: Run actionlint
      run: |
        ./actionlint -color .github/workflows/ci-cd.yml
        echo "Workflow validation successful!" 